### ISSUE TITLE
Plugin options are not displayed in Joomla 3.4.5

### ISSUE THREAD

**Issue by luby1** [marneu/joomlatic#2]
![image001](https://cloud.githubusercontent.com/assets/15990545/11354492/aa720220-92b0-11e5-9bfd-1b4151b5f377.png)

When trying to configure the plugin, the options do not show the text, but show the option name instead. However, the plugin still works if we choose the option based on the position in the Features section of the documentation (i.e. selecting first position for logging events does log all events).

I hope this is not something very complicated to fix. Thanks.

**Comment by marneu** [comment]
Should be fixed within 1.3
