### ISSUE TITLE
Language file format incorrect

### ISSUE THREAD

**Issue by prophoto** [marneu/joomlatic#3]
See docs https://docs.joomla.org/Specification_of_language_files. You need to add quotes to all of your translation strings.

`
PLG_SYSTEM_SYSLOGAUTHLOG="System - Syslog AuthLog"
PLG_SYSTEM_SYSLOGAUTHLOG_DESCRIPTION="A syslog authentication logger for Joomla - activate Plugin and set your options."
PLG_SYSTEM_SYSLOGAUTHLOG_XML_DESCRIPTION="Set your options for the plugin System - Syslog AuthLog and activate it to use it."
PLG_SYSTEM_SYSLOGAUTHLOG_MODE_DESC="Logging mode"
PLG_SYSTEM_SYSLOGAUTHLOG_MODE_LABEL="Log mode"
PLG_SYSTEM_SYSLOGAUTHLOG_MODE_ALL="successful and failure"
PLG_SYSTEM_SYSLOGAUTHLOG_MODE_ERROR="only log failure"
PLG_SYSTEM_SYSLOGAUTHLOG_EVENT_DESC="Logging events"
PLG_SYSTEM_SYSLOGAUTHLOG_EVENT_LABEL="Log events"
PLG_SYSTEM_SYSLOGAUTHLOG_EVENT_ALL="login and logout"
PLG_SYSTEM_SYSLOGAUTHLOG_EVENT_LOGIN="login only"
PLG_SYSTEM_SYSLOGAUTHLOG_EVENT_LOGOUT="logout only"
PLG_SYSTEM_SYSLOGAUTHLOG_TYPE_DESC="Log user event type (frontend or backend)"
PLG_SYSTEM_SYSLOGAUTHLOG_TYPE_LABEL="Log user event type"
PLG_SYSTEM_SYSLOGAUTHLOG_TYPE_ALL="frontend and backend events"
PLG_SYSTEM_SYSLOGAUTHLOG_TYPE_ADMIN="backend events only"
`

**Comment by marneu** [comment]
Thanks for letting me know. Please use 1.5, the corrected version

**Comment by prophoto** [comment]
Sure
